# Generated by Django 3.0.7 on 2020-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述'),
        ),
    ]
